 --CATALOGO: TIPO DE EVENTO
CREATE TABLE tipo_evento (
    tipo_evento_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre            VARCHAR2(150) NOT NULL,
    descripcion       VARCHAR2(500)
);
COMMENT ON TABLE tipo_evento IS 'Catálogo de tipos de eventos de seguridad del paciente.';
COMMENT ON COLUMN tipo_evento.nombre IS 'Nombre del tipo de evento, e.g. Caídas, Medicación, IAAS.';

CATALOGO: SEVERIDAD (OMS A–I)
CREATE TABLE severidad (
    severidad_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo          CHAR(1) NOT NULL,
    descripcion     VARCHAR2(300)
);
COMMENT ON TABLE severidad IS 'Catálogo de severidad del evento (A–I según OMS).';
COMMENT ON COLUMN severidad.codigo IS 'Código A–I.';
🔹 2. PACIENTE E INGRESOS
 TABLA: PACIENTE
CREATE TABLE paciente (
    paciente_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_doc           VARCHAR2(5),
    num_doc            VARCHAR2(20),
    nombre_completo    VARCHAR2(200),
    fecha_nacimiento   DATE,
    sexo               CHAR(1)
);
COMMENT ON TABLE paciente IS 'Información básica del paciente.';
 --TABLA: INGRESO / ATENCIÓN
CREATE TABLE ingreso (
    ingreso_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paciente_id     NUMBER NOT NULL,
    fecha_ingreso   DATE NOT NULL,
    servicio        VARCHAR2(100),
    cama            VARCHAR2(40),
    estado          VARCHAR2(20),

    CONSTRAINT fk_ingreso_paciente
        FOREIGN KEY (paciente_id)
        REFERENCES paciente(paciente_id)
);

COMMENT ON TABLE ingreso IS 'Registro de ingresos o episodios clínicos.';
--TABLA: EVENTO
CREATE TABLE evento (
    evento_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ingreso_id        NUMBER NOT NULL,
    tipo_evento_id    NUMBER NOT NULL,
    severidad_id      NUMBER NOT NULL,
    fecha_evento      DATE NOT NULL,
    descripcion       VARCHAR2(2000),
    detectado_por     VARCHAR2(150),
    es_incidente      CHAR(1),
    es_evento_adverso CHAR(1),
    es_casi_falla     CHAR(1),
    estado            VARCHAR2(30),
    fecha_reporte     DATE,
    usuario_reporte   VARCHAR2(100),

    CONSTRAINT fk_evento_ingreso
        FOREIGN KEY (ingreso_id)
        REFERENCES ingreso(ingreso_id),
    CONSTRAINT fk_evento_tipo
        FOREIGN KEY (tipo_evento_id)
        REFERENCES tipo_evento(tipo_evento_id),
    CONSTRAINT fk_evento_severidad
        FOREIGN KEY (severidad_id)
        REFERENCES severidad(severidad_id)
);

COMMENT ON TABLE evento IS 'Eventos de seguridad del paciente, incluyendo incidentes, near miss y eventos adversos.';
🔹 4. ANÁLISIS DEL EVENTO
sql
Copiar código
 --TABLA: ANALISIS DEL EVENTO
CREATE TABLE analisis_evento (
    analisis_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evento_id           NUMBER NOT NULL,
    tipo_analisis       VARCHAR2(100),
    causa_primaria      VARCHAR2(1000),
    causas_contrib      VARCHAR2(1500),
    acciones_inmediatas VARCHAR2(1500),
    acciones_recomend   VARCHAR2(2000),
    responsable         VARCHAR2(150),
    fecha_cierre        DATE,

    CONSTRAINT fk_analisis_evento
        FOREIGN KEY (evento_id)
        REFERENCES evento(evento_id)
        ON DELETE CASCADE
);

COMMENT ON TABLE analisis_evento IS 'Análisis RCA, Ishikawa o AMFE del evento reportado.';

--TABLA: ACCIONES DE MEJORA
CREATE TABLE accion_mejora (
    accion_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evento_id        NUMBER NOT NULL,
    descripcion      VARCHAR2(1500),
    responsable      VARCHAR2(150),
    fecha_programada DATE,
    fecha_ejecucion  DATE,
);